#cloud-config
users: # Array von Usern die erstellt werden
  - name: ubuntu # Username
    sudo: ALL=(ALL) NOPASSWD:ALL # Der Benutzer kann alle Befehle als jeder benutzer (sudo) ausführen und muss dafür kein Passwort eingeben
    groups: users, admin # Der Benutzer ist in den Gruppen users und admin
    home: /home/ubuntu # Home Verzeichnis des Benutzers
    shell: /bin/bash # Shell des Benutzers
    ssh_authorized_keys: # Array von SSH Keys 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU1B7+jwdy08QksJMs+swxlmIAShQnxtkoXbdLrE4rWktWEUGQHpwJWr/9+PSGcFUxgsvEHcAFzR59WKwB4uL1PCaGDeAxL+2h2W4jyt/sF20Q7J6haJe/7Ke5YK5EZpmcWtI5lQmxDoL32NFYRrp5pnjZ9lxGLvIyO8xMiYSrzqPqzW58P2Cf6vQXIE5bCq+KWRCSE3T9/ZTMrGoSCC5/v+AotFVwRbK8+tPS/8hGG4MfMkdXCk2vwCxcuzrei0CZl1lhsubBajjBsdVyckbDY0oOoWIVgP5Jmnaho1/bZaKUl7FEMU8ULOQfq+kiJLxX01ww7AUQTCrvR7CzTwrv aws-key
ssh_pwauth: false # SSH Passwort Authentifizierung ist deaktiviert
disable_root: false # Der Root Benutzer ist nicht deaktiviert
package_update: true # Paketliste wird aktualisiert
packages: # Array von Paketen die installiert werden
  - curl 
  - wget 
