#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU1B7+jwdy08QksJMs+swxlmIAShQnxtkoXbdLrE4rWktWEUGQHpwJWr/9+PSGcFUxgsvEHcAFzR59WKwB4uL1PCaGDeAxL+2h2W4jyt/sF20Q7J6haJe/7Ke5YK5EZpmcWtI5lQmxDoL32NFYRrp5pnjZ9lxGLvIyO8xMiYSrzqPqzW58P2Cf6vQXIE5bCq+KWRCSE3T9/ZTMrGoSCC5/v+AotFVwRbK8+tPS/8hGG4MfMkdXCk2vwCxcuzrei0CZl1lhsubBajjBsdVyckbDY0oOoWIVgP5Jmnaho1/bZaKUl7FEMU8ULOQfq+kiJLxX01ww7AUQTCrvR7CzTwrv aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl 
  - wget 
  - mariadb-server
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service